### ISSUE TITLE
Certain timestamps cannot be set

### ISSUE THREAD

**Issue by gitbbkload** [limbenjamin/nTimetools#6] opened 2021-09-14 14:39 UTC
`nTimestomp_v1.2_x64.exe -F "C:\Users\flroida\Desktop\1601.txt" -M "1601-01-01 00:00:00.0000000" -A "1601-01-01 00:00:00.0000000" -C "1601-01-01 00:00:00.0000000" -B "1601-01-01 00:00:00.0000000"`

```
nTimestomp, Version 1.2
Copyright (C) 2019 Benjamin Lim
Available for free from https://limbenjamin.com/pages/ntimetools

mchgachgFilesystem type:                NTFS
Filename:                       C:\Users\flroida\Desktop\test.txt
File size:                      0

File timestamp successfully set

[M] Last Write Time:            2021-09-14 23:24:26.3232770 UTC
[A] Last Access Time:           2021-09-14 23:24:26.3232770 UTC
[C] Metadata Change Time:       2021-09-14 23:24:36.6512444 UTC
[B] Creation Time:              2021-09-14 23:24:26.3232770 UTC
```

Problem:
The timestamps were not set.

---

`nTimestomp_v1.2_x64.exe -F "C:\Users\flroida\Desktop\9999.txt" -M "9999-12-31 23:59:59.9999999" -A "9999-12-31 23:59:59.9999999" -C "9999-12-31 23:59:59.9999999" -B "9999-12-31 23:59:59.9999999"`

```
nTimestomp, Version 1.2
Copyright (C) 2019 Benjamin Lim
Available for free from https://limbenjamin.com/pages/ntimetools

mchgachgFilesystem type:                NTFS
Filename:                       C:\Users\flroida\Desktop\test.txt
File size:                      0

File timestamp successfully set

[M] Last Write Time:            9999-12-31 23:59:59.99999999 UTC
[A] Last Access Time:           9999-12-31 23:59:59.99999999 UTC
[C] Metadata Change Time:       9999-12-31 23:59:59.99999999 UTC
[B] Creation Time:              9999-12-31 23:59:59.99999999 UTC
```
Problem:
The timestamps have been set. But the output shows an 8 digit number for the nanosecond field instead of a 7 digit number for the nanosecond field.

**Comment by limbenjamin** [comment] 2021-09-14 16:20
Won't fix. No practical use for setting date to 1601. Additional digit likely caused by floating point value. Does not meet bar for servicing.

**Closed as completed by limbenjamin** 2021-09-14 16:20 UTC
